version: "3.5"
services:

  hugo:
    build:
      context: .
      dockerfile: Dockerfile-hugo
    volumes:
      - .:/site
      - output-ru:/site/public/ru
      - output-en:/site/public/en
    command: "hugo server --buildDrafts --watch --baseURL http://dm --bind 0.0.0.0"
    ports:
      - "1313:1313"
      - "1314:1314"

  s3-website-ru:
    build:
      context: .
      dockerfile: Dockerfile-s3-website
    volumes:
      - output-ru:/output:ro
      - ./s3_website.yml:/s3_website.yml:ro
    env_file:
      - .env
    environment:
      - S3_BUCKET=andreyfedoseev.ru
      - CLOUDFRONT_DISTRIBUTION_ID=E2YSUW7AO72069
      - DOMAIN=andreyfedoseev.ru

  s3-website-en:
    build:
      context: .
      dockerfile: Dockerfile-s3-website
    volumes:
      - output-en:/output:ro
      - ./s3_website.yml:/s3_website.yml:ro
    env_file:
      - .env
    environment:
      - S3_BUCKET=andreyfedoseev.com
      - CLOUDFRONT_DISTRIBUTION_ID=E2YJI7MAL9CA6I
      - DOMAIN=andreyfedoseev.com

volumes:
  output-ru:
  output-en:
